### ISSUE TITLE
Redis6 Support.

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#328]
[redis-doc diff](https://github.com/antirez/redis-doc/compare/233c4cdd96e48273bff51bf30d23b7ee75b39b53...dd4159397f115d53423c21337eedb04d3258d291#diff-e2571e1121887e3a7e1bf9d686e0ffce)

### File Changes

- [x]  commands.json                 | 255 ++++++++++++++++++++++++++++++++++++--
- [x]  commands/acl-cat.md           |  82 +++++++++++++
- [x]  commands/acl-deluser.md       |  16 +++
- [x]  commands/acl-genpass.md       |  43 +++++++
- [x]  commands/acl-list.md          |  17 +++
- [x]  commands/acl-load.md          |  23 ++++
- [x]  commands/acl-log.md           |  35 ++++++
- [x]  commands/acl-save.md          |  18 +++
- [x]  commands/acl-setuser.md       |  78 ++++++++++++
- [x]  commands/acl-users.md         |  15 +++
- [x]  commands/acl-whoami.md        |  14 +++
- [x]  commands/auth.md              |  36 ++++--
- [ ]  commands/bgsave.md            |  18 ++-
- [ ]  commands/client-caching.md    |  22 ++++
- [ ]  commands/client-getredir.md   |  11 ++
- [x]  commands/client-kill.md       |   1 +
- [ ]  commands/client-tracking.md   |  33 +++++
- [ ]  commands/hello.md             |  40 ++++++
- [ ]  commands/migrate.md           |   2 +
- [ ]  commands/stralgo.md           | 104 ++++++++++++++++
- [ ]  commands/xinfo.md             |  73 +++++++++++
- [x]  modules.json                  |  40 ++++--
- [x]  tools.json                    |   7 ++
- [x]  topics/acl.md                 |  26 +++-
- [x]  topics/client-side-caching.md |  25 +++-
- [x]  topics/cluster-tutorial.md    |   4 +-
- [x]  topics/data-types.md          |   2 +-
- [x]  topics/indexes.md             |   2 +-
- [x]  topics/notifications.md       |   8 +-
- [x]  topics/sentinel-old.md        | 587 ----------------------------------------------------------------------------------------

### TODO

- [x] test `AUTH ****` cli test ,for both 5 and 6
- [x] test all doc renders (https://github.com/laixintao/iredis/pull/324#issuecomment-624095002)
- [x] `ACL *` Command implementation
- [x] `BGSAVE` suooprt `schedule`
- [x] `CLIENT CACHING`
- [x] `CLIENT GETREDIR`
- [x] `CLIENT TRACKING`
- [x] `HELLO`
- [x] `STRALGO`
- [x] `AUTH` command support user & password[doc](https://github.com/antirez/redis-doc/compare/233c4cdd96e48273bff51bf30d23b7ee75b39b53...dd4159397f115d53423c21337eedb04d3258d291#diff-3dcca43f12987c32bff467aba6aa47ba)
- [x] client kill  `CLIENT KILL USER `username (see docs)
- [x] migrate auth2 [doc](https://github.com/antirez/redis-doc/compare/233c4cdd96e48273bff51bf30d23b7ee75b39b53...dd4159397f115d53423c21337eedb04d3258d291#diff-69fc7b19b63d7000fa0da9292f3e438b)
- [x] xinfo [doc](https://github.com/antirez/redis-doc/compare/233c4cdd96e48273bff51bf30d23b7ee75b39b53...dd4159397f115d53423c21337eedb04d3258d291#diff-7313636ed82edbb988d50f33d10126f9)

## Support RESP3
